<?php
/**
 * Skopiowane z vendor/magento/module-theme/view/frontend/templates/html/copyright.phtml
 * (Etap 9 planu nauki) — oryginał w vendor zostaje nietknięty, to nadpisanie
 * przez child theme.
 */
?>
<small class="copyright">
    <!--
        TODO (Etap 9, pkt 2 — "zmień coś widocznego"): dopisz/zmień dowolny
        widoczny element tutaj albo w web/css/source/_module.less. To jest
        Twój child theme — eksperymentuj bez ryzyka zepsucia oryginału.
    -->
    <span><?= $block->escapeHtml($block->getCopyright()) ?></span>
</small>
